### ISSUE TITLE
Stlye the Sign Up view.

### ISSUE THREAD

**Issue by germanruzca** [BC-MAY-21-ROR/proyecto-final-k8-f22-t2-local-e-commerce#9]
# REQUIREMENTS
Style the design from the Figma design.

# DESIGN
<img width="575" alt="image" src="https://user-images.githubusercontent.com/43076503/162840720-48d6e551-2293-4d0b-a752-322973f6d3b3.png">

# Acceptance Criteria
- [ ] Use the buttons created in the #8 issue
- [ ] Use the inputs created in the #8 issue
- [ ] Style the view based in the Figma design. #2
